sudo: required
services:
    - docker

# before_install:
#   - docker build -t vineeth97/Docker-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run vineeth97/Docker-test npm test -- --coverage

after_success:
  - docker build -t vineeth97/multi-client ./client
  - docker build -t vineeth97/multi-nginx ./nginx
  - docker build -t vineeth97/multi-server ./server
  - docker build -t vineeth97/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push vineeth97/multi-client
  - docker push vineeth97/multi-nginx
  - docker push vineeth97/multi-server
  - docker push vineeth97/multi-worker