sudo: required
services:
    - docker

before_install:
  - docker build -t VineethReddy02/Docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run VineethReddy02/Docker-test npm test -- --coverage

after_success:
  - docker build -t VineethReddy02/multi-client ./client
  - docker build -t VineethReddy02/multi-nginx ./nginx
  - docker build -t VineethReddy02/multi-server ./server
  - docker build -t VineethReddy02/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push Vineeth97/multi-client
  - docker push Vineeth97/multi-nginx
  - docker push Vineeth97/multi-server
  - docker push Vineeth97/multi-worker